name: Windows build

on:
  workflow_dispatch: # manually-triggered workflow

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test1
        run: |
          uname -a

      - name: Prepare environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: 'MINGW64'
          update: true
          install: mingw-w64-x86_64-libtool mingw-w64-x86_64-openssl mingw-w64-x86_64-curl mingw-w64-x86_64-python mingw-w64-x86_64-cython mingw-w64-x86_64-toolchain mingw-w64-x86_64-autotools

      - name: Build project
        run: |
          uname -a
          which libtoolize
          bash ./build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libimobiledevice-dist-windows
          path: ./dist/*
